# This is a template file for development. DO NOT commit actual secrets to version control.
# Instead, create secrets using kubectl or a secrets management solution.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/energy_monitor
  SESSION_SECRET: your-local-dev-secret
  TELEGRAM_BOT_TOKEN: your-telegram-bot-token
  OPENWEATHERMAP_API_KEY: your-openweathermap-api-key
  ADMIN_CHAT_ID: your-admin-chat-id